baseurl: '/personal-website'
permalink: pretty
title: 'Felix Holz'
footer_text: 'Felix Holz, Graz, Austria'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_projects: 6

collections:
  projects:
    output: true
    sort_by: weight
  photography:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ''
      type: 'photography'
    values:
      layout: 'photograph'

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
